FROM python:3.9 as app
RUN mkdir /app
WORKDIR /app

RUN pip install --upgrade pip

COPY ./requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

COPY ./src /app/src
COPY ./bin /app/bin
COPY ./storage /app/storage

CMD [ "python", "-m", "bin.mining.StartMiningOperations", "userAddress"]